#The title of the workbench. If you change this, any existing CRAPI workbenches will be broken

workbenchtitle: "&e&lSpecial Crafting"
recipebook: "&e&lRecipe Book"
nextpage: "&e&lNext Page"
currentpage: "Current page"
previouspage: "&e&lPrevious Page"
customrecipeview: "&e&lCustom Recipe View"
customrecipecreator: "&e&lCustom Recipe Creator"
fullinv: "&cInventory is full. Cannot craft item."
invalidrecipe: "&cInvalid Recipe"
createrecipe: "&aCreate Custom Recipe"
toggleshapeless: "&9Toggle Shapeless Recipe"
shaped: "Shaped"
leftclicktoview: "&7Left click to view recipe."
rightclicktogive: "&7Right click to give yourself this item."
permission: "Permission"
backtomenu: "&cBack to Menu"
deleterecipe: "&cDelete Recipe"
cannotbeundone: "&7cannot be undone"
recipeview: "&7Recipe View"