name: CustomRecipeAPI
version: 1.2.0
main: me.darkolythe.customrecipeapi.CustomRecipeAPI
api-version: 1.13

commands:
  crapi:
    usage: /<command>
    aliases: [customrecipeapi]
    description: the CRAPI command
    permission: crapi.command
    permission-message: You do not have permission!

permissions:
  crapi.command:
    description: Allows the use of CRAPI commands
    default: op
  crapi.book:
    description: Allows the use of the CRAPI recipe book
    default: op
  crapi.giveitem:
    description: Allows the use of the CRAPI recipe book to give items
    default: op
  crapi.new:
    description: Lets the user create new recipes in-game
    default: op